# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'DittoCoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DittoCoreData
  pod "DittoSwift", ">=1.0.4"

  # Used for generating random fake data
  pod "Fakery"

  pod "CodableWrappers"
  pod "DeepDiff"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
