platform :ios, '10.0'
use_frameworks!

target 'DittoChat' do
    pod 'DittoMeshKit', '~> 2.3'
    pod 'Chatto', '= 3.3.1'
    pod 'ChattoAdditions', '= 3.3.1'
    pod 'Cartography'
    pod 'Eureka', '= 4.1.1'
    pod 'RSKPlaceholderTextView'
end
